# Generated by Django 3.2.8 on 2021-10-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodszyfru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='cipher',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
