# Generated by Django 3.2.8 on 2021-10-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodszyfru', '0003_alter_passwords_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='cipher',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
